rules:
  leading-zero: 0
  function-name-format:
    - 1
    - allow-leading-underscore: false
      convention: camelcase
  mixin-name-format:
    - 1
    - allow-leading-underscore: false
      convention: camelcase
  placeholder-name-format:
    - 1
    - allow-leading-underscore: false
      convention: camelcase
  class-name-format:
    - 1
    - allow-leading-underscore: false
      convention: camelcase
  nesting-depth:
    - 1
    - max-depth: 3