[general]
host = "127.0.0.1"
port = 8081
message_max_time = 10 # In ms.
verbose_log = true
log_path = "/tmp"
remote_services_config = "./remote/config.toml"
remote_services_path = "./remote"
socket_path = "/tmp/api-daemon-socket"

[http]
root_path = "api-daemon/http_root"

[telemetry]
enabled = false
token_uri = ""
metrics_uri = ""

[vhost]
root_path = "profile/webapps/installed"
csp = "default-src * data: blob:; script-src 'self' http://127.0.0.1:8081 http://shared.localhost:8081; object-src 'none'; style-src 'self' 'unsafe-inline' http://shared.localhost:8081"
report_csp = true

[apps_service]
root_path = "profile/webapps"
data_path = "profile/webapps"
uds_path = "/tmp/apps_service_uds.sock"
cert_type = "development"
updater_socket = "/tmp/updater_socket"
user_agent = "Mozilla/5.0 (Mobile; rv:110.0) Gecko/110.0 Firefox/110.0 B2GOS/2023.1 OrchidOS/3.5"
allow_remove_preloaded = true

[procmanager_service]
socket_path = "/tmp/b2gkiller_hints"
hints_path = "/tmp/prochints.dat"

[content_manager]
storage_path = "/sdcard"
metadata_cache_capacity = 250

[dweb]
storage_path = "/dweb"
